#%RAML 1.0 Library
usage:
traits:
  errorResponses: !include /libraries/common/errorResponses/errorResponses.raml
  transactionId: !include /libraries/traits/transactionId.raml
  departureLocation: !include /libraries/traits/queryParamsdepartureLocation.raml
  destinationLocation: !include /libraries/traits/queryParamsDestinationLocation.raml
